apiVersion: 1

datasources:
  - name: Loki
    type: loki
    uid: loki
    access: proxy
    url: http://loki:3200
    basicAuth: false
    jsonData:
      maxLines: 1000
      derivedFields:
        - name: traceID
          datasourceUid: tempo
          matcherRegex: '(?:"traceID"\:")(\w*)(?:")'
          url: '$${__value.raw}'
          urlDisplayLabel: 'Traces'
        - name: traceID
          datasourceUid: prometheus
          matcherRegex: '(?:"traceID"\:")(\w*)(?:")'
          url: '$${__value.raw}'
          urlDisplayLabel: 'Metrics'
