apiVersion: 1

datasources:
  - name: Tempo
    type: tempo
    uid: tempo
    url: http://tempo:3200
    access: proxy
    basicAuth: false
    jsonData:
      tracesToLogsV2:
        datasourceUid: 'loki'
        spanStartTimeShift: '30m'
        spanEndTimeShift: '-30m'
        tags: 
          - key: service.name
            value: job
        filterByTraceID: false
        filterBySpanID: false
        customQuery: true
        query: '{$${__tags}} | json | traceID="$${__trace.traceId}"'
#      tracesToMetrics:
#        datasourceUid: 'prometheus'
#        spanStartTimeShift: '1h'
#        spanEndTimeShift: '-1h'
#        tags: [{ key: 'service.name', value: 'service' }, { key: 'job' }]
#        queries:
#          - name: 'Metrics query'
#            query: 'sum(rate(traces_spanmetrics_latency_bucket{$$__tags}[5m]))'
      serviceMap:
        datasourceUid: 'prometheus'
      nodeGraph:
        enabled: true
      search:
        hide: false
      lokiSearch:
        datasourceUid: 'loki'
      traceQuery:
        timeShiftEnabled: true
        spanStartTimeShift: '1h'
        spanEndTimeShift: '-1h'
      spanBar:
        type: 'Tag'
        tag: 'http.path'
